export enum HW5_Events {
    PLAYER_MOVE = "PlayerMove",
    PLAYER_JUMP = "PlayerJump",
    PLAYER_HIT_ENEMY = "PlayerHitEnemy",
    PLAYER_ENTERED_LEVEL_END = "PlayerEnteredLevelEnd",
    LEVEL_START = "LevelStart",
    LEVEL_END = "LevelEnd",
    PLAYER_KILLED = "PlayerKilled",
    GRAVITY_UP = "GavityUp",
    GRAVITY_DOWN = "GavityDown",
    GRAVITY_LEFT = "GavityLeft",
    GRAVITY_RIGHT = "GavityRight",
    FLIP = "Flip",
    OUT = "Out",
    TRANSITION_START = "TransitionStart",
    FLOAT_UP = "FloatUp",
    FLOAT_DOWN = "FloatDown",
    RESPAWN = "Respawn",
    INVINCIBLE = "invincible"
}